### ISSUE TITLE
Galeri Dataset

### ISSUE THREAD

**Issue by oyilmaztekin** [elyface/elyface-SSR#109]

**Comment by zekpehlivan** [comment]
Verisettte type_Galeri olarak hazırlandı.

**Comment by zekpehlivan** [comment]
Birde Manşet alanında "Galeri" filtresi yapıldı. Manset datasetinde "Haber" ve "Galeri" olarak 2 tip filtre kullanıldı.

**Comment by oyilmaztekin** [comment]
Manşet altındaki galeri ile ilgili biraz bilgi verebilir misin. Anlamadım orayı

**Comment by zekpehlivan** [comment]
Aynı şekilde Çok Okunanlar datasetine Haber Galeri filtre tipi kullanıldı. 
Tüm veri setlerde aynı filtre mantığını kullanıyorum.

**Comment by zekpehlivan** [comment]
Şimdi Manşet Altı içerik tipi. Ben "Manşet" veri setinde filtre olarak galeri girdim birde. O da içerik konumu haber eklemede ayrı api id si ile geliyor, galeride ayrı.
![Screen Shot 2019-03-13 at 15 24 43](https://user-images.githubusercontent.com/47023940/54278720-3a810d80-45a4-11e9-95dd-4492c2624b36.png)
![Screen Shot 2019-03-13 at 15 24 53](https://user-images.githubusercontent.com/47023940/54278721-3a810d80-45a4-11e9-9aeb-8970e0417107.png)

**Comment by oyilmaztekin** [comment]
Doğru anladıysam manşet imiz istersek galeri istersek de haber olarak sunulabiliyor. Peki bu galeriyi nasıl kullanacağız şimdi? Manşet olarak yukarıda, galeri tipiyle de aşağıda mı kullanıyor olacağız?

**Comment by zekpehlivan** [comment]
Şöyle bir durum. Galeri Manşette de görünmesi gerekebilir. O zaman önce haber filtresi sonra galeri filtresini kullanırız. Olur mu acaba böyle bişey?
