### ISSUE TITLE
Kategori Sayfaları

### ISSUE THREAD

**Issue by oyilmaztekin** [elyface/elyface-SSR#117]
- [x] Gündem
- [x] Siyaset
- [x] Ekonomi
- [x] Spor
- [x] Yaşam
- [x] Magazin
- [x] emlak
- [x] Eğitim #114 çözüldüğünde çalışacak...
- [x] teknoloji
- [x] Seyahat #115 çözüldüğünde çalışacak......

**Comment by zekpehlivan** [comment]
Seyahat ve emlak kategori eklendi.
