### ISSUE TITLE
Google DFP - React Entegrasyonu

### ISSUE THREAD

**Issue by oyilmaztekin** [elyface/elyface-SSR#19]
Bu konu biraz çetrefilli. Bunu buradan tartışmak, bağlantıları paylaşmak daha uygun olacak.
#80

**Comment by zekpehlivan** [comment]
Burada example var;
https://www.npmjs.com/package/react-dfp

Google DFP id; 61966246

**Comment by zekpehlivan** [comment]
![screen shot 2019-02-13 at 14 39 42](https://user-images.githubusercontent.com/47023940/52709295-6b6a2480-2f9d-11e9-9ee3-146dfd0bfb16.png)
Şu an sayfadaki kullanım şekli.

**Comment by zekpehlivan** [comment]
![screen shot 2019-02-13 at 14 40 56](https://user-images.githubusercontent.com/47023940/52709329-8472d580-2f9d-11e9-8412-993ae714027c.png)
Burada da yayınlama şekli.

**Comment by zekpehlivan** [comment]
google.com/dfp 

adresinden giriş yapabilirsin.

ozer.yilmaztekin@elluga.com   mailini yönetici olarak tanımladım. 

Mantığı şöyle;

1 - Envanter tanımlıyorsun. ( Bunu biz yapıyoruz ) Boyutu şekli şemali tanımlanıyor. 

2 - Bu reklam birimi için daha sonra etiket tanımlanıyor.

Bu etikette sayfaya ekleniyor.

Mantığı bu şekilde.

![etiket1](https://user-images.githubusercontent.com/47023940/52709736-9acd6100-2f9e-11e9-9514-f67ea56fb529.png)
![etiket2](https://user-images.githubusercontent.com/47023940/52709737-9b65f780-2f9e-11e9-994a-d73b652b013d.png)
![reklambirimi](https://user-images.githubusercontent.com/47023940/52709738-9b65f780-2f9e-11e9-9f60-64036034ee0c.png)
![yenireklambirim](https://user-images.githubusercontent.com/47023940/52709739-9b65f780-2f9e-11e9-9a84-c5192e718387.png)

**Comment by oyilmaztekin** [comment]
Abi ellerine sağlık gayet güzel anlatmışsın. Ben bununla alakalı olarak bi araştırma yapayım detaylı başlamadan önce.

**Comment by oyilmaztekin** [comment]
- react-dfp bizim [state manager](https://github.com/elluga/haberiyakalaSSR/blob/413236f1145f0147a1048dca1aac9de8075bb01e/pages/newsdetail.js#L13)  #102 da olduğu gibi... implementasyonu ile aynı altyapıyı kullandığı için çakışma olmaması için iyi kurgulmak lazım.   

- Bir de asıl test edilmesi gereken bir şey var; **bir sayfada sadece bir tane `DFPSlotsProvider` kullanabiliyoruz.** Aşağıdaki kodda  `Adslot` componenti her bir reklam gösterim alanını ifade ediyor. InfiniteScroll kullandığımız için sıradaki `Article` componenti oluştuğu zaman `AdSlot`componentini oluşturacağız. Yani `DFPSlotsProvider` componentini her article özel ayarlayamayız.

```javascript
 <DFPSlotsProvider dfpNetworkId={'9999'} adUnit={"foo/bar/baz"} ... >
         ...
         <AdSlot adUnit={"home/leaderboard"} sizes={[ [900, 90], [728, 90]]} />
         ...
         /* you can override the props */
         <AdSlot adUnit={"home/mobile"} sizes={[ [300, 250], [300, 600]]} />
         ...
         <div>
           ...
           <AdSlot adUnit={"home/footer"} sizes={[ [300, 250], [300, 600]]} />
           ...
         </div>
         ...
       </DFPSlotsProvider>
```
 

> DFPSlotsProvider: this component is only meant to configure global options, it follows the context provider pattern ( see this link for details ), you should only declare and mount one instance of this component per page (tipically as higher as possible on the tree so all the nodes can access the context variables.)

#### Detaylı dökümantasyon - http://react-dfp.tk/examples/basic/

**Comment by oyilmaztekin** [comment]
##### örnek dataset
- `reklam-dfp`

#### Blupoint reklam analizi - `response` 
- `type` : `reklam_alani_dfp`
- `Yayıncı ID` = `dfpNetworkId` : 61966246 ( hesap yönetici id si)
-  ❌ `reklam_birimi_adi`= _div_id_ : `anasayfa_masthead`
- ✅ `reklam_birimi_adi`= _div_id_ : `AnasayfaMastHead` ( panel script i nasıl veriyorsa... ) 
- ❓ `reklam_birimi_id` : `1550058370232-0` - google'dan `div-gpt-ad-1553767868243-0` şeklinde veriliyor. Şu an gereksiz gibi görünüyor.

#### Belge başlığı - `<head>` kodları

```javascript
<script async='async' src='https://www.googletagservices.com/tag/js/gpt.js'></script>
<script>
  var googletag = googletag || {};
  googletag.cmd = googletag.cmd || [];
</script>

<script>
  googletag.cmd.push(function() {
    googletag.defineSlot('/61966246/AnasayfaMastHead', [970, 250], 'div-gpt-ad-1553767868243-0').addService(googletag.pubads());
    googletag.pubads().enableSingleRequest();
    googletag.enableServices();
  });
</script>
```

#### gövde - div alan kodu
```javascript
<!-- /61966246/AnasayfaMastHead -->
<div id='div-gpt-ad-1553767868243-0' style='height:250px; width:970px;'>
<script>
googletag.cmd.push(function() { googletag.display('div-gpt-ad-1553767868243-0'); });
</script>
</div>
```

**Comment by oyilmaztekin** [comment]
@zekpehlivan 
### DFP structure

- Herhangi bir page için dataset kullanılacak. 
- `CardManager` veya `cards` componenti için dataset içerisinde reklam content i. ( `cat-gundem` içerisine gömülmüş reklam content i gibi. O datasette kaç tane reklam göstereceksek... )  
- `InfiniteScroll` için de dataset kullanalım... (`one-cikanlar` içerisine de gömülebilir kategoriye göre ayrı dataset de olabilir `one-cikanlar-reklam-dfp`gibi...)

**Comment by oyilmaztekin** [comment]
@zekpehlivan **anasayfa_sol1** için iki tane genişlik ve yükseklik parametresi geliyor bana. Bunlar nasıl çalışıyor tam olarak? Aşağıdaki örneği baz alırsak mesela`160x600`, `120x800`şeklinde mi? 

```JSON 
{
"boyut_genislik": "160,120", 
"boyut_yukseklik": "600,800"
}
```

**Comment by zekpehlivan** [comment]
Aynen dediğin gibi, 160x600, 600x800 olarak çalışıyor.

**Comment by zekpehlivan** [comment]
@oyilmaztekin Bu ikili sistem oluyor değil mi?

**Comment by oyilmaztekin** [comment]
@zekpehlivan ayarlarız bir şekilde doğrusu buysa. `react-dfp`de buna uygun bir kullanım var. [`sizes`](http://react-dfp.tk/adslot/sizes/) olarak geçiyor. Daha ileri seviye kullanımlar için de  [`sizeMappping`](http://react-dfp.tk/adslot/sizemapping/) var. Mesela tarayıcı boyutuna göre kullanımlar için `sizeMapping` yapıyoruz.

**Comment by zekpehlivan** [comment]
Okdir. Kategori bazında da ekleme yaptım...

Bir inceleyebilirsin...

Gündem masthead ve sag alan 300x250 olarak yaptım...

**Comment by oyilmaztekin** [comment]
`AdSlot` componenti sadece `DFPProvider` context wrapper ı ile aynı seviyede çalışıyor. Child componentlerde `AdSlot` çalışmıyor.
