### ISSUE TITLE
Header ve Sayfalama için SEO ayarları

### ISSUE THREAD

**Issue by oyilmaztekin** [elyface/elyface-SSR#21]
**Seo ayarları ve geliştirme standartları** belirlemek için API sonuçlarını bekliyoruz. Ancak yine de her sayfada header kısmında bulunması gereken tag leri belirlemek lazım. 

Standartlarımızı buradan tartışabiliriz.

[Örnek Plugin](https://github.com/garmeeh/next-seo)

**Comment by zekpehlivan** [comment]
Burada https://zeo.org/tr/teknik-seo-checklist/ cehecklist bulunuyor. Belki işimize yarar. 

Birde PageSpeed İnsights bulunuyor.

https://developers.google.com/speed/pagespeed/insights/

Sayfa analizleri ile alakalı.
