### ISSUE TITLE
infinity scroll / router link (detay sayfası) komponenti

### ISSUE THREAD

**Issue by oyilmaztekin** [elyface/elyface-SSR#22]
Bazı örnek komponentler mevcut. Bunları uyarlayabilir miyiz değerlendirmek lazım. 

https://www.npmjs.com/package/react-infinite-scroller 
https://www.npmjs.com/package/react-infinite-scroll-component

**Comment by zekpehlivan** [comment]
Şimdi bu örneklerde infinite scroll çalışıyor ancak burada içeriği paging olarak update ediyor. Buradaya kadar okdir.

Makale olayında şöyle bir durum var; haber linkininde değişmesi gerekiyor.

Neden dersek kullanıcı "domain.com/x-haber" diye bir makaleyi açsın.

Sayfayı scrool ettikçe "y haber" "domain.com/y-haber" olmazsa bu sefer içerik değişse bile linki kopyalayıp paylaştığında "domain.com/x-haber"  kopyalaşmış oluyor. 

<img width="1427" alt="screen shot 2019-02-13 at 15 03 24" src="https://user-images.githubusercontent.com/47023940/52710544-a3bf3200-2fa0-11e9-8914-dc2df642a1c0.png">

Mesela ben burada "div - #7" yi görüyorum. Ama sana linki verdiğimde sen baştan başlıyorsun.

https://yk7637p62z.codesandbox.io/

**Comment by zekpehlivan** [comment]
Şurada abiler tartışmış galiba;

https://stackoverflow.com/questions/51244908/change-url-with-reactjs-infinite-scrolling

**Comment by oyilmaztekin** [comment]
Anladım hem içerik hem de paylaşım için router linki değişecek. Bunun için bi komponent yazarız muhtemelen. Veya yukarıda paylaştığım komponentlerden birisini değiştiririz.

**Comment by oyilmaztekin** [comment]
#110 öne çıkanlar datasetinden yükleme yapılacak.

**Comment by oyilmaztekin** [comment]
#80 #19 scroll edildiğinde, haber değiştiğinde reklam güncellenecek.

**Comment by oyilmaztekin** [comment]
Örnek: https://codesandbox.io/s/yk7637p62z

**Comment by zekpehlivan** [comment]
Bunda şöyle bir sıkıntı vardı yanlış hatılamıyorsam ; 
üstte linkte div-id basmıyor. Böylece link paylaşıldığında aynı sayfaya gidiyor sürekli...

**Comment by oyilmaztekin** [comment]
Evet aynen öyle. Diğer paketlerde de var o sıkıntı. Çünkü tamamı lazy loading mantığında kurgulanmış. O kısmı biz kendimiz yazacağız.

**Comment by zekpehlivan** [comment]
[files.zip](https://github.com/elluga/haberiyakalaSSR/files/2991837/files.zip)

**Comment by zekpehlivan** [comment]
İnfiniti dosyaları ekledim. Görebilirsin.

**Comment by oyilmaztekin** [comment]
`DFP` ile alakalı işlemler `DFPSlotsProvider` ın deklare edildiği sayfada yapılabiliyor. `StoreProvider` üzerinde `activeURL` değişimi olduğunda  `pagedetaillayout` komponenti içerisinde `DFPManager.refresh()` uygulanacak.
