### ISSUE TITLE
Blue Point CMS İçerik Örnek

### ISSUE THREAD

**Issue by zekpehlivan** [elyface/elyface-SSR#33]
İçerik ID - JSON Örneği

"_id": "5c5ee0bd17ff6d0007030d71",
  "domain_id": "5c4984af5a4da10008e77628",
  "base_type": "content",
  "type": "haber_ekleme",
  "start_date": "2019-02-09T14:16:29.124000Z",
  "title": "Yalçın Menteş son yolculuğuna uğurlandı",
  "description": "Yalçın Menteş ölüm haberi",
  "status": "active",
  "path": "/",
  "url": "/yalcin-mentes-son-yolculuguna-ugurlandi-17",
  "template_id": null,
  "membership_id": "sadece_haber",
  "sys": {
    "created_at": "2019-02-09T14:16:29.822000Z",
    "created_by": "sadece_haber",
    "modified_at": "2019-02-09T14:19:10.506000Z",
    "modified_by": "sadece_haber",
    "collection": "published_contents",
    "version": 2,
    "cid": 1958,
    "domain_cid": 17,
    "synchronized_at": "2019-02-09T14:19:20.684000Z",
    "published_at": "2019-02-09T14:19:20.739000Z",
    "published_version": 2,
    "published_by": "sadece_haber",
    "first_published_at": "2019-02-09T14:19:20.763000Z",
    "first_published_by": "sadece_haber"

**Comment by zekpehlivan** [comment]
Bu arada sol alandan "Alan Adları" sekmesinden "Haberi Yakala" seçildiğinde böyle bir ekranla karşılaşıyoruz;
Burada ön izleme url var.

<img width="1435" alt="screen shot 2019-02-14 at 14 45 39" src="https://user-images.githubusercontent.com/47023940/52784800-58238b80-3067-11e9-9832-ecc18eaa85c9.png">

**Comment by oyilmaztekin** [comment]
Anladım. Bu sadece tek bir content in örneği. Tüm content leri alıp sayfada göstereceğim tüm haberlerle alakalı bir json dönmesi lazım ilk etapta. Farazi olarak belirtmek gerekirse `haber_id` sini de buradan alıp, detayına tıkladığında `content_id` ile detay göstereceğim.
